# Uncomment this line to define a global platform for your project
#  platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EasyGoing' do

pod 'AFNetworking'
pod 'SnapKit', '~> 0.30.0.beta2'
pod 'MBProgressHUD'
pod 'SwiftyJSON', '~> 2.4.0'
pod 'FMDB'
pod 'SAMKeychain'
pod 'BlocksKit'
pod 'SDWebImage'
pod 'AVOSCloud', '~> 3.6.1'
pod 'pop'
pod 'IQKeyboardManager'
pod 'JCAlertView'               #TimeLine模块-消费项目弹出视图
pod 'Masonry'
#pod 'Charts', '~> 2.3.1'
#pod 'LeanCloudSocial'           #leanCloud登录模块

end

